name: dart_crawler
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  html: ^0.14.0+3
  http: ^0.12.1
  path_provider: ^1.6.8

dev_dependencies:
  pedantic: ^1.8.0
